tunnel: 2bcc66e6-36d1-47de-93f4-43e48e5b58c7
credentials-file: C:/Users/Suphawit/.cloudflared/2bcc66e6-36d1-47de-93f4-43e48e5b58c7.json

ingress:
  # อันนี้สำหรับหน้าเว็บหลัก
  - hostname: gacha.telemedicproject.dpdns.org
    service: http://localhost:3000
    originRequest:
      httpHostHeader: localhost:3000

  # อันนี้สำหรับ API รับเงิน (พอร์ต 3001)
  - hostname: api-gacha.telemedicproject.dpdns.org
    service: http://localhost:3001

  - service: http_status:404